# Generated by Django 4.0.4 on 2022-06-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=100)),
                ('isGraduated', models.BooleanField(default=False)),
            ],
        ),
    ]
