# Generated by Django 4.0.4 on 2022-05-17 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
    ]
